Add `--with-metadata` support for workflow:dump command
zerodahero/laravel-workflow pull request #97
Opened 2024-10-28 05:35 UTC by cfong63

Hopefully its explained in the README changes.

Largely just exposing symfony's `--with-metadata` option for dumping workflow

2024-10-28 11:47 UTC, zerodahero requested changes
Thanks for adding this in! Let's make the change to match the casing here (camelCase), and then it should be good to go.

2024-10-28 11:47 UTC, zerodahero commented on src/Commands/WorkflowDumpCommand.php
> +        $dumper_options = [
Let's match the style in this codebase of camel-cased names
```suggestion
        $dumperOptions = [
```

2024-10-28 11:47 UTC, zerodahero commented on src/Commands/WorkflowDumpCommand.php
> +        $process->setInput($dumper->dump($definition, options: $dumper_options));
```suggestion
        $process->setInput($dumper->dump($definition, options: $dumperOptions));
```

2024-10-29 00:08 UTC, cfong63 commented
Done and done, thanks for maintaining the project :)

2024-10-29 01:58 UTC, cfong63 commented
Updated to fix the broken existing tests

2024-10-29 23:32 UTC, cfong63 commented
🤦‍♂️ just learning now that symfony's metadata dumping has a 8.1 dependency

2024-10-30 00:43 UTC, zerodahero commented
> 🤦‍♂️ just learning now that symfony's metadata dumping has a 8.1 dependency.
> 
> I'm not versed in how to handle cross-version dependencies. Any quick thoughts? Simplest thing would be to skip this in php 8.0 test and bump the doco I'm guessing but that seems a bit hack-ish

I'm fine dropping support for PHP 8.0, it's dead now anyway. I think it's fair to bump this a major version to note that drop--so we can merge that in and I'll fix up the matrix before cutting the 6.0 release here.

2024-10-30 00:43 UTC, merged